<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

subsetting: selecting a subset of the data in a list or array. can be done through
1. indexing (1 element) or
2. slicing (range of elements)

arrays are good to store different kinds of data while lists are good for math 

numpy lists are difficult to lengthen but python lists are easier 

clarify how to centralise and align 

In [3]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]


In [4]:
py_list[0]

'a1'

In [5]:
py_list[2]

'c3'

In [8]:
py_list[1:6]    #expected number of elements = 6 -1 = 5
                #for a general formula of py_list[x, y] where y > x, expected no. of elements = y - x 


['b2', 'c3', 'd4', 'e5', 'f6']

In [10]:
py_list[1:6:2]      #py_list[x:y:z], x is the start, y is the end element and z is the number of steps between each element 

['b2', 'd4', 'f6']

In [13]:
py_list [2::5]       #go from 3rd element to the last element, skipping 5 in between

['c3', 'h8']

In [15]:
py_list [5:]         #6th element all the way to the last 

['f6', 'g7', 'h8', 'i9', 'j10']

In [16]:
py_list [:5]          #first element all the way to the 6th element 

['a1', 'b2', 'c3', 'd4', 'e5']

In [18]:
py_list [5:2]         #nothing because going from the start to the back but 5>2] 

[]

In [20]:
py_list[5:2:-1]       #to work, need to instruct the code to go from the last to the first element 

['f6', 'e5', 'd4']

In [22]:
py_list[::-1]          #all the elements but in reverse order 

['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']

## 1.2 Arrays only | Subsetting by masking

masking: show me all the true ones but dont show me all the alse ones 

In [35]:
import numpy as np

np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [36]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [37]:
np_array[np_array > 3]    #removing the need for the variable my_mask


array([ 4,  5,  6,  7,  8,  9, 10])

In [40]:
np_array[~(np_array > 3)]                 # '~' means 'NOT'(bitwise not operator. we can also use invert.numpy()

array([1, 2, 3])

In [41]:
np_array[(np_array > 3) & (np_array < 8)] # '&' means 'AND'

array([4, 5, 6, 7])

In [42]:
np_array[(np_array < 3) | (np_array > 8)] # '|' means 'OR'

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [79]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

print(np_array_2d)

[['1' 'A']
 ['2' 'B']
 ['3' 'C']
 ['4' 'D']
 ['5' 'E']
 ['6' 'F']
 ['7' 'G']
 ['8' 'H']
 ['9' 'I']
 ['10' 'J']]


In [44]:
py_list_2d[3]

[4, 'D']

In [44]:
py_list_2d[3]

[4, 'D']

In [47]:
np_array_2d[3]    #now the number 4 is converted from an integer to a string type. in array, everyhing is converted into string 

array(['4', 'D'], dtype='<U21')

In [51]:
py_list_2d[3][0]    #the number within the first [] specifies which element of the larger list to take out, 
                    #while the second [] specifies the element within the smaller list 

4

In [53]:
np_array_2d[3, 0]     #the number before the comma specifies which element of the larger list to take out, 
                      #while number after the comma specifies the element within the smaller list 

'4'

In [54]:
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [55]:
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

In [60]:
py_list_2d[:3][0]     #clarify, shoulnt it be 1,2,3

[1, 'A']

In [61]:
np_array_2d[:3, 0]    #yep shouldnt the one before this be be similar to this 

array(['1', '2', '3'], dtype='<U21')

In [62]:
np_array_2d[:, 0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

## 1.4 Growing lists

In [64]:
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

methods to adding single elements to the list 

clarify - what is a touble , what is the difference between identity and type 

#method 1
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

In [67]:
#method 2
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [69]:
#method 3
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

methods to adding multiple elements to the list 


In [74]:
#method 1
x = [1, 2, 3]
x += [4, 5, 6]
x

[1, 2, 3, 4, 5, 6]

In [75]:
#method 2
x=[1, 2, 3]
x.extend([4, 5, 6])
x

[1, 2, 3, 4, 5, 6]

In [78]:
#method 3
x=[1, 2, 3]
x.append([4, 5, 6])
x                            #note that the append allows us to add lists to a list, unlike the extend command which adds all the elements 
                             #as individual elements in the list. use append to add lists to a list

[1, 2, 3, [4, 5, 6]]

In [65]:
#for lists, we can change the value of a specific element. however, for tuples, we cannot change the values, like set in stone  

# Some loose ends

## 1.5 Tuples

## 1.6 Be VERY careful when copying

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes