<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# Subsetting: Indexing and Slicing

In [ ]:
# subsetting - selecting a subset of the data in a list or array through 
# method 1: selecting one element - indexing 
# method 2: selecting a range of elements - slicing 

## Lists & Arrays in 1D | Subsetting & Indexing

In [17]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]

print(py_list[0]) 
print(py_list[2])
print(py_list[1:6])         # expected number of elements = 6 -1 = 5. for py_list[x, y] where y > x, expected no. of elements = y - x

print(py_list[1:6:2])       # py_list[x:y:z], x is the start, y is the end element and z is the number of steps between each element 
print(py_list [2::5])       # go from 3rd element to the last element, skipping 5 in between

print(py_list [5:])         # 6th element all the way to the last
print(py_list [:5])         # first element all the way to the 6th element 

print(py_list [5:2])        # nothing because going from the start to the back but 5 > 2
print(py_list[5:2:-1])      # to make code work, need to instruct the code to go from the last to the first element
print(py_list[::-1])        # all the elements but in reverse order

a1
c3
['b2', 'c3', 'd4', 'e5', 'f6']
['b2', 'd4', 'f6']
['c3', 'h8']
['f6', 'g7', 'h8', 'i9', 'j10']
['a1', 'b2', 'c3', 'd4', 'e5']
[]
['f6', 'e5', 'd4']
['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']


In [5]:
import numpy as np 

py_list = ["hibiscus", "tulip", "rose", "dandelion", "baby's breath",
         "hydrangea", "orchid", "sunflower", "gerbera", "morning glory"]

np_array = np.array(py_list)

x = np_array

In [16]:
print(x[0])                # gives first element 
print(x[-1])               # gives last element 

print(x[0:3])              # gives the first 4 elements 
print(x[2:4])              # gives the third, fourth and fifth element 
print(x[2:8:2])            # from index 2 to 8 in steps of 2. gives the third, fifth and seventh elements 

print(x[:3])               # gives all elements up to the 3th element 
print(x[7:])               # gives all elements after the 7th element 

print(x[8:4:-1])           # gives all elements from the 9th element (index 8) up till the 6th element(index 5), in the reverse order
print(x[::-1])             # gives all elements in the reserve order 

hibiscus
morning glory
['hibiscus' 'tulip' 'rose']
['rose' 'dandelion']
['rose' "baby's breath" 'orchid']
['hibiscus' 'tulip' 'rose']
['sunflower' 'gerbera' 'morning glory']
['gerbera' 'sunflower' 'orchid' 'hydrangea']
['morning glory' 'gerbera' 'sunflower' 'orchid' 'hydrangea'
 "baby's breath" 'dandelion' 'rose' 'tulip' 'hibiscus']


## Arrays only | Subsetting by masking

masking: show me all the true ones but not the false ones 

In [18]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [19]:
np_array[my_mask]     # command to make an array of all the elements that fulfil the condition i.e True 

array([ 4,  5,  6,  7,  8,  9, 10])

In [37]:
np_array[np_array > 3]    # removing the need for the variable my_mask

array([ 4,  5,  6,  7,  8,  9, 10])

In [40]:
np_array[~(np_array > 3)]                 # '~' means 'NOT'

array([1, 2, 3])

In [41]:
np_array[(np_array > 3) & (np_array < 8)] # '&' means 'AND'

array([4, 5, 6, 7])

In [42]:
np_array[(np_array < 3) | (np_array > 8)] # '|' means 'OR'

array([ 1,  2,  9, 10])

## Lists & Arrays in 2D | Indexing & Slicing

In [30]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

np_array_2d

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C'],
       ['4', 'D'],
       ['5', 'E'],
       ['6', 'F'],
       ['7', 'G'],
       ['8', 'H'],
       ['9', 'I'],
       ['10', 'J']], dtype='<U21')

In [44]:
py_list_2d[3]

[4, 'D']

In [47]:
np_array_2d[3]    #now the number 4 is converted from an integer to a string type. in array, everyhing is converted into string 

array(['4', 'D'], dtype='<U21')

In [51]:
py_list_2d[3][0]    #the number within the first [] specifies which element of the larger list to take out, 
                    #while the second [] specifies the element within the smaller list 

4

In [32]:
np_array_2d[3][0]

'4'

In [53]:
np_array_2d[3, 0]     #the number before the comma specifies which element of the larger list to take out, 
                      #while number after the comma specifies the element within the smaller list 

'4'

In [34]:
py_list_2d[3,0]       #can use either [3][0] or [3,0] for arrays but only can use [3][0] for lists 

TypeError: list indices must be integers or slices, not tuple

In [37]:
py_list_2d[:3]      

[[1, 'A'], [2, 'B'], [3, 'C']]

In [55]:
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

In [39]:
## take note of the differences in what list and arrays give when 2 indexes are used 

print(py_list_2d[:3][0])     # note that its not [1,2,3]. [:3] gives [[1,'A'][2,'B'][3,'C']]. 
                             # [0] hence takes the first element of this new list which is [1,'A'] 

print(np_array_2d[:3, 0])    # note that [:3, 0] gives different outputs than [3][0] for arrays  

print(np_array_2d[:3][0])    

[1, 'A']
['1' '2' '3']
['1' 'A']


In [40]:
print(np_array_2d[:, 0])
# compared to 
print(np_array_2d[:][0])    # = print(np_array_2d[0])

['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']
['1' 'A']


## Growing lists (not arrays!)

In [ ]:
## benefits of using lists vs arrays 
# lists: ease and efficiency in growing list 
# arrays: better for math operations (if we are not changing their size) 

In [41]:
x=[1, 2]*5    # recall difference in multiplying a list and an array by a constant
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [57]:
## 3 methods to grow a list by appending on element at a time 

# main learning points: 
# 1. to add on multiple elements at once, use extend() or '+='. both works for numbers and string! 
# 2. append() runs at higher speeds than the other 2 methods 

In [42]:
#method 1
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [67]:
#method 2
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [69]:
#method 3
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

In [47]:
## differences between using method 1,2 and 3 -> the execution speeds differ. append() runs about 1.5 times faster 

In [55]:
# using extend() instead of append()

x = ['brie']
x.extend(['cheddar', 'gouda', 'mozarella', 'camembert'])
x 

['brie', 'cheddar', 'gouda', 'mozarella', 'camembert']

In [54]:
x = ['brie'] 
x.append('cheddar', 'gouda', 'mozarella', 'camembert') #list.append() can only take 1 argument i.e one element at a time 
x                                                      #to add on multiple elements at once, use extend()

TypeError: list.append() takes exactly one argument (4 given)

In [66]:
## methods to adding multiple elements to the list at once 


In [63]:
#method 1 (for both numbers and string)
x = [1, 2, 3]
x += [4, 5, 6]
print(x)

y = ['brie'] 
y += ['cheddar', 'gouda', 'mozarella', 'camembert']
print(y) 

[1, 2, 3, 4, 5, 6]
['brie', 'cheddar', 'gouda', 'mozarella', 'camembert']


In [64]:
#method 2 (for both numbers and string)
x=[1, 2, 3]
x.extend([4, 5, 6])
x

[1, 2, 3, 4, 5, 6]

In [65]:
#method 3 (only for numbers, not string)
x=[1, 2, 3]
x.append([4, 5, 6])
print(x)                     #note that the append allows us to add lists to a list, unlike the extend command which adds all the elements 
                             #as individual elements in the list. use append to add lists to a list

y = ['brie']
y.append('cheddar', 'gouda', 'mozarella', 'camembert')
print(y)   

[1, 2, 3, [4, 5, 6]]


TypeError: list.append() takes exactly one argument (4 given)

## Tuples

In [70]:
#tuples are similar to lists except 1. cannot change or add values in the tuple 2. data stored within () and not []

list_1 = [11,22,33,44]
list_1[1] = 21 
print(list_1)

tuple_1 = (11,22,33,44) 
tuple_1[1] = 21
print(tuple[1])

[11, 21, 33, 44]


TypeError: 'tuple' object does not support item assignment

In [74]:
tuple_1 = (11,22,33,44) 
tuple_1 += 21
print(tuple[1])     #cannot add on new elements to the tuple. we need to make another new tuple 

TypeError: can only concatenate tuple (not "int") to tuple

In [72]:
# however, indexing can still work on tuples to draw out values 
tuple_1[3] 

44

## Be VERY careful when copying (lists or arrays)

In [85]:
# whenever we want to copy a list/array, use _.copy() function and not '=' function 

# wrong way: 
tic = [121,153,178,197]     # when we use '=', all 3 lists have the same ID 
tac = tic 
toe = tic 

print(id(tic))
print(id(tac))
print(id(toe))      

tic += [223, 257, 289]      # adding to one of the lists results in ALL 3 lists being changed 
print(tic)                   
print(tac) 
print(toe)

print(id(tic))              # despite the change in the lists, note that the ID number remains the same 
print(id(tac))
print(id(toe))  

4491308544
4491308544
4491308544
[121, 153, 178, 197, 223, 257, 289]
[121, 153, 178, 197, 223, 257, 289]
[121, 153, 178, 197, 223, 257, 289]
4491308544
4491308544
4491308544


In [86]:
#instead do: 
tic = [121,153,178,197]
tac = tic.copy()            # when we use .copy(), all 3 lists have different IDs 
toe = tic.copy()

print(id(tic))
print(id(tac))
print(id(toe))      

tic += [223, 257, 289]      # adding to one of the lists still leaves the other 2 lists unaffected 
print(tic)                  
print(tac) 
print(toe)

print(id(tic))             
print(id(tac))             
print(id(toe))

4490886976
4490596992
4490844096
[121, 153, 178, 197, 223, 257, 289]
[121, 153, 178, 197]
[121, 153, 178, 197]
4490886976
4490596992
4490844096
