<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

In [1]:
import numpy as np

non-comprehensive list of ways to store and manipulate data 
1. lists
2. numpy arrays
3. dictionaries
4. tuples
5. dataframes
6. classes 

# Lists, Arrays & Dictionaries

## Let’s compare

a. Python lists

In [3]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [2]:
this = ["coffee", "sun", "python"]
that = ["tea", "moon", "R"] 

b. Numpy arrays

In [5]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [3]:
np_this = np.array(["coffee", "sun", "python"])
np_that = np.array(["tea", "moon", "R"])

c. Dictionary

In [5]:
#the first name in each line is the key and the second name is the value 
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

In [28]:
x=superhero_info.keys()  #cannot take index from dictionary 


In [37]:
list(x)[0]    
#to take out a specific item from the list, we need to index the list, tuple or array. 
#have to convert the dictionary to either of these first

'Natasha Romanoff'

In [39]:
this_or_that = {
    "coffee" : "tea", 
    "sun": "moon", 
    "python" : "R"
}   #order matters since first element is always key and second element is always value 


## Accessing data from a list (or array)

In [49]:
#converting a dictionary to a list 
list_this_or_that = list(this_or_that)
array_this_or_that = np.array(this_or_that)   #note that array() is a command belonging to numpy module so cannot just put 'array(this_or_that)'

print(list_this_or_that)
print(array_this_or_that)
print(this_or_that)

['coffee', 'sun', 'python']
{'coffee': 'tea', 'sun': 'moon', 'python': 'R'}
{'coffee': 'tea', 'sun': 'moon', 'python': 'R'}


In [50]:
print(list_this_or_that[1])
list_this_or_that[1]      #note the difference between simply calling out the index vs printing the called out indexed element 

sun


'sun'

## Accessing data from a dictionary

In [52]:
#functions of dictionaries 

this_or_that.items()

dict_items([('coffee', 'tea'), ('sun', 'moon'), ('python', 'R')])

In [53]:
this_or_that.keys()

dict_keys(['coffee', 'sun', 'python'])

In [54]:
this_or_that. values()

dict_values(['tea', 'moon', 'R'])

In [58]:
 this_or_that["tea"]    #cannot pull out key using the value 

KeyError: 'tea'

In [60]:
this_or_that["coffee"]    #can only pull out value using the key 

'tea'

## Higher dimensional lists

In [65]:
#instead of having 2 lists for the keys and the values, instead just use a 2D list 

py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

ls_this_or_that = [['coffee', 'tea'], 
                   ['sun', 'moon'],
                   ['python', 'R']]     #remember to include a comma between 2 elements in a smaller list 
                                        #and to include a comma between smaller list within the bigger list


In [72]:
ls_this_or_that[1]  #taking out one of the smaller lists 

['sun', 'moon']

In [73]:
ls_this_or_that[1][1]  #taking out an element of the smaller lists 


'moon'

In [74]:
(ls_this_or_that[1])[1]   #also works!

'moon'

# Lists vs. Arrays

important to take note of the similarities and differences between lists and arrays 

## Size

In [78]:
# for lists and arrays, len() gives the length i.e only the number of lists within the larger list 
len(list_this_or_that)    #even with
len (this_or_that)
# for arrays, var.shape gives both the number of lists within the larger list and the number of elements within each small list 

3

In [77]:
len (this_or_that)

3

In [82]:
x = 10
y = x  #  here, before any of the 2 variables are modified, they have the same id 
x += 2   # here, once x is modified, the id of the two variables are different. (ref. to nice to know for more info)
         #variables will have different ids when the type of data they store or the value of the data differs. 
y 

10

In [90]:
test_array = np.array([[1,2],[3,4],[5,6]])
test_array     #this will also give an output, no need for print(test_array) because in jupyter notebook, the last line  of code will always give an output 

array([[1, 2],
       [3, 4],
       [5, 6]])

In [91]:
len(test_array)  

3

In [94]:
test_array.shape    #shape gives (number of rows, number of columns)


(3, 2)

## Arrays are fussy about type (lists not so fussy)

In [97]:
#arrays will only have a single data type while lists can accommodate different data types 

py_list = [3,6,'woohoo']
np_array = np.array(py_list)
print(np_array)     # if we convert a list with both str and int to an array, the array converts numbers to str 

['3' '6' 'woohoo']


## Adding a number

In [102]:
py_list = [1,2,3,4,5] 
np_array = np.array(py_list)

# can add a constant to ALL the elements in an array
# can treat arrays as a variable in a mathematical operation 

np_array + 10 

array([11, 12, 13, 14, 15])

In [104]:
np_array[2] + 10 #we can also use index to add a constant to a single element in the array 

13

In [105]:
py_list + 10   #we can add constants to ALL elements in arrays but not to lists simultaneously 


TypeError: can only concatenate list (not "int") to list

In [107]:
py_list[2] + 10  #however, we can add constants to a specific element in a list 

13

## Adding another list

In [108]:
SEA_list = ['Cambodia', 'Indonesia', 'Laos', 'Singapore', 'Philipines']
Asian_list = ['China', 'Japan', 'Russia', 'Kazakhstan', 'India']

SEA_array = np.array(SEA_list)
Asian_array = np.array(Asian_list) 

print(SEA_list)     
print(SEA_array)   


['Cambodia', 'Indonesia', 'Laos', 'Singapore', 'Philipines']
['Cambodia' 'Indonesia' 'Laos' 'Singapore' 'Philipines']


In [110]:
SEA_list + Asian_list 
SEA_array + Asian_array    #adding of list to list or arrays to arrays does not work if the elements are characters 

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U10'), dtype('<U10')) -> None

## Multiplying by a Number

In [7]:
import numpy as np 

odd_list = [1,3,5,7,9,11,13,15]
even_list = [2,4,6,8,10,12,14,16] 

odd_array = np.array(odd_list)
even_array = np.array(even_list)


In [5]:
odd_list + even_list 

[1, 3, 5, 7, 9, 11, 13, 15, 2, 4, 6, 8, 10, 12, 14]

In [12]:
print(len(odd_array))
print(len(even_array))
odd_array + even_array  #the length of the arrays being added must be of the same length 

8
8


array([ 3,  7, 11, 15, 19, 23, 27, 31])

In [22]:
# multiplication does not work for lists but works for arrays 

## Squaring

In [23]:
# squaring does not work for lists but works for arrays 

## Asking questions

In [25]:
# do not ask py_list == 3 (works but is not an answer to 'is 3 inside the list') FOR LIST
# can ask np_array == 3. asking will give a list of true or false answer for each of the elements in the array 

# do not ask py_list >3 
# can ask np_array > 3, this is asking if each of the elements (numbers) are greater than 3 or not 

# can ask np_array.sum() - asking for the total value after adding all the elements in the array together
# asking sum for list works too 

## Mathematics

# Exercises & Self-Assessment

In [ ]:



# Your solution here


